### ISSUE TITLE
Supporting neovim plugins such as Treesitter etc.

### ISSUE THREAD

**Issue by aasutossh** [atelierbram/Base2Tone-vim#10]

**Comment by atelierbram** [comment]
This repo is for the classical setup and will most likely stay how it is. For NeoVim please use [Base2Tone-nvim](https://github.com/atelierbram/Base2Tone-nvim) which is written in Lua and specially adapted with Treesitter. It supports quite a few of the popular plugins like Telescope, Nvim-Tree, IndentBlankline, GitSigns.
