### ISSUE TITLE
Renaming of files

### ISSUE THREAD

**Issue by atelierbram** [atelierbram/Base2Tone-vim#2]
The files for the colorschemes of Base2Tone-vim, which now comes with support for [Airline](https://github.com/vim-airline/vim-airline) have been renamed from `Base2Tone-<scheme>-dark` to `Base2Tone_<scheme>Dark  `.  

So instead of defining in vimrc:

```
colorscheme Base2Tone-evening-dark  
``` 

it is now:

```
colorscheme Base2Tone_EveningDark  
``` 

I'm sorry for the inconvenience, (it was a templating issue).
I could have kept the old files (which content in fact has not changed) around for a bit, to avoid breaking colorschemes on update, but this will annoy new users, I can imagine, so either way we can not win. Hope this note will make a difference.

**Comment by nmihaica** [comment]
`Base2Tone_eveningDark` is not working for me. 
`Base2Tone_EveningDark` is the correct solution. Same goes for the other schemes.

**Comment by atelierbram** [comment]
@nmihaica thanks for the heads up!
