### ISSUE TITLE
distribute with Vim?

### ISSUE THREAD

**Issue by chrisbra** [atelierbram/Base2Tone-vim#3]
there is an [issue](https://github.com/vim/vim/issues/1665) open in the vim repository, to distribute more colorschemes with Vim. Would you kindly give your permission to distribute this colorscheme with Vim?

**Comment by atelierbram** [comment]
How could I say no to a request like this? ;) Great! But there are many variations in there, like the ones that were converted from Simurai's themes for Atom, like the default light theme, here named Base2Tone-MorningLight. Besides that one only Heath, (Base2Tone-HeathLight) looks really good inversed IMO, so I would advice against including any of the others in light background. However all of the dark ones look really good, I've  grown especially fond of Drawbridge-Dark, which I have been using for over a year now and am still not bored by it. So yes, permission given 👌

**Comment by chrisbra** [comment]
Oh, in that case I would suggest simply pick one good looking dark theme and contribute that.

I would prefer if you can send it to Bram or vim-dev, since you know obviously best, when it is kind of stable enough and of course you will know when to send updated themes to Bram for inclusion. 

You should mention that you are the author and give permission to have the file distributed with Vim. Make sure to mention issue vim/vim#1665 and whenever an update is needed please send an updated file to Bram. Thanks!

**Comment by atelierbram** [comment]
OK so I did that, I hope I send it to the right place [over here](https://groups.google.com/forum/#!topic/vim_dev/IpzAKmGub1Y)

**Comment by chrisbra** [comment]
thanks that was the correct place.
