### ISSUE TITLE
Neovim terminal git status untracked files

### ISSUE THREAD

**Issue by adrian-martinez-dev** [atelierbram/Base2Tone-vim#5]
Hi, it's posible to change the color from git status output for untracked files, to something more readable?, currently it looks like this, thanks in advance!
![captura de pantalla de 2018-06-05 14-18-35](https://user-images.githubusercontent.com/5392962/40997775-653ba3d4-68cb-11e8-954a-d1c66224d4d8.png)

**Comment by atelierbram** [comment]
Thanks for the feedback, I am going to look into this ... Out of curiosity, can you tell me which terminal on which OS? (Having issues with the combination Hyper(term)-Neovim on Mac OS X myself lately.)

**Comment by adrian-martinez-dev** [comment]
Fedora 28, Gnome Terminal 3.28.2

Edit: NeovimGtk screenshot, same issue
Edit: I forgot to say that it's the neovim embedded terminal

**Comment by atelierbram** [comment]
Thanks for the info, this is very helpful! (I bet this is a "Neovim embedded terminal thing" 😏)

**Comment by atelierbram** [comment]
@nbicalcarata I found and checked the fix for this issue and just pushed the fix. When you pull & check & confirm this working for you then I can close this issue.

**Comment by adrian-martinez-dev** [comment]
It works!, thank you so much!

**Comment by atelierbram** [comment]
You are welcome, have a nice day!
