### ISSUE TITLE
Matching paren/braces 

### ISSUE THREAD

**Issue by imjasonmiller** [atelierbram/Base2Tone-vim#7]
Hi Bram!

I just noticed that the colors for matching braces or parentheses make the cursor difficult to see in neovim as illustrated below, with my cursor being on the left side in both cases. 

```vim
call <sid>hi("MatchParen",    s:gui00, s:gui03, s:cterm00, s:cterm03,  "")
```

Before | After
---|---
![image](https://user-images.githubusercontent.com/12190184/73128349-3b5d3b00-3fce-11ea-93c3-48b883505b73.png) | ![image](https://user-images.githubusercontent.com/12190184/73128267-e0771400-3fcc-11ea-8126-4cd0a66b55d4.png)

I'm not sure whether this is a problem on my end, but after changing `MatchParen` to the following it seems to be easier to see:

```vim
call <sid>hi("MatchParen",    s:gui0A, s:gui02, s:cterm0A, s:cterm02,  "")
```
Is a pull request welcome?

**Comment by atelierbram** [comment]
Thanks for this, I don't think this is solely a problem on your end, as far as I can see; it makes sense having a bit more contrast for these matching parens/bracens _(, although it never bothered me to be honest)_. I just pushed your proposed edits, also for light themes. Please let me know if this doesn't work for you.

**Comment by imjasonmiller** [comment]
Thank you! :+1: More than happy to be of help.
